#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to the $branch branch"
  exit 1
fi

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to the $branch branch"
  exit 1
fi