name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          npm install
      - name: VSCE
        run: |
          npm install -g vsce
      - name: Compile
        run: |
          npm run compile
      - name: Package
        run: |
          vsce package
      - name: Publish
        run: |
          vsce publish -p ${{ secrets.ACTIONS }}
