name: Test
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
      - run: |
          npm install -g vsce
      - run: |
          npm run compile
          npm run test
